### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Sunshine19980919** [PengBoXiangShang/deepchange#1]
Hello, paying tribute to your outstanding work!

I have seen that you have contributed an excellent dataset. Recently, I am preparing to build a small pedestrian re identification dataset. In order to quickly and effectively build small private datasets, we would like to ask you for some insights and experiences on building datasets from video files.

Best wishes to you!

**Comment by PengBoXiangShang** [comment]
thanks. it would be good to give me emails.
